//! H.264 CAVLC (Context-Adaptive Variable Length Coding) 熵解码。
//!
//! 用于解码 4x4 块的残差系数，包含 coeff_token、trailing_ones 符号、
//! level、totalZeros 和 run_before 的 VLC 解码。

use crate::video::h264::bitstream::BitReader;
use crate::video::h264::tables::ZIGZAG_4x4;

/// CAVLC 解码结果：4x4 残差系数（Zigzag 顺序填充）。
#[derive(Debug, Clone)]
pub struct CavlcResult {
    #[allow(dead_code)]
    pub coeffs: [i16; 16],
    pub total_coeff: u32,
}

// ═══ AUTO-GENERATED by gen_cavlc_tables.py ═══
// Source: FFmpeg h264_cavlc.c — DO NOT EDIT MANUALLY
// Tables sorted by codeword length ascending (required by match_vlc)

/// Num-VLC0: nC ∈ [0, 2)
const COEFF_TOKEN_VLC0: &[(u32, u8, u32, u32)] = &[
    (0b1, 1, 0, 0),
    (0b01, 2, 1, 1),
    (0b001, 3, 2, 2),
    (0b00011, 5, 3, 3),
    (0b000101, 6, 1, 0),
    (0b000100, 6, 2, 1),
    (0b000011, 6, 4, 3),
    (0b0000101, 7, 3, 2),
    (0b0000100, 7, 5, 3),
    (0b00000111, 8, 2, 0),
    (0b00000110, 8, 3, 1),
    (0b00000101, 8, 4, 2),
    (0b00000100, 8, 6, 3),
    (0b000000111, 9, 3, 0),
    (0b000000110, 9, 4, 1),
    (0b000000101, 9, 5, 2),
    (0b000000100, 9, 7, 3),
    (0b0000000111, 10, 4, 0),
    (0b0000000110, 10, 5, 1),
    (0b0000000101, 10, 6, 2),
    (0b0000000100, 10, 8, 3),
    (0b00000000111, 11, 5, 0),
    (0b00000000110, 11, 6, 1),
    (0b00000000101, 11, 7, 2),
    (0b00000000100, 11, 9, 3),
    (0b0000000001111, 13, 6, 0),
    (0b0000000001011, 13, 7, 0),
    (0b0000000001110, 13, 7, 1),
    (0b0000000001000, 13, 8, 0),
    (0b0000000001010, 13, 8, 1),
    (0b0000000001101, 13, 8, 2),
    (0b0000000001001, 13, 9, 2),
    (0b0000000001100, 13, 10, 3),
    (0b00000000001111, 14, 9, 0),
    (0b00000000001110, 14, 9, 1),
    (0b00000000001011, 14, 10, 0),
    (0b00000000001010, 14, 10, 1),
    (0b00000000001101, 14, 10, 2),
    (0b00000000001001, 14, 11, 2),
    (0b00000000001100, 14, 11, 3),
    (0b00000000001000, 14, 12, 3),
    (0b000000000001111, 15, 11, 0),
    (0b000000000001110, 15, 11, 1),
    (0b000000000001011, 15, 12, 0),
    (0b000000000001010, 15, 12, 1),
    (0b000000000001101, 15, 12, 2),
    (0b000000000000001, 15, 13, 1),
    (0b000000000001001, 15, 13, 2),
    (0b000000000001100, 15, 13, 3),
    (0b000000000001000, 15, 14, 3),
    (0b0000000000001111, 16, 13, 0),
    (0b0000000000001011, 16, 14, 0),
    (0b0000000000001110, 16, 14, 1),
    (0b0000000000001101, 16, 14, 2),
    (0b0000000000000111, 16, 15, 0),
    (0b0000000000001010, 16, 15, 1),
    (0b0000000000001001, 16, 15, 2),
    (0b0000000000001100, 16, 15, 3),
    (0b0000000000000100, 16, 16, 0),
    (0b0000000000000110, 16, 16, 1),
    (0b0000000000000101, 16, 16, 2),
    (0b0000000000001000, 16, 16, 3),
];

/// Num-VLC1: nC ∈ [2, 4)
const COEFF_TOKEN_VLC1: &[(u32, u8, u32, u32)] = &[
    (0b11, 2, 0, 0),
    (0b10, 2, 1, 1),
    (0b011, 3, 2, 2),
    (0b0101, 4, 3, 3),
    (0b0100, 4, 4, 3),
    (0b00111, 5, 2, 1),
    (0b00110, 5, 5, 3),
    (0b001011, 6, 1, 0),
    (0b000111, 6, 2, 0),
    (0b001010, 6, 3, 1),
    (0b001001, 6, 3, 2),
    (0b000110, 6, 4, 1),
    (0b000101, 6, 4, 2),
    (0b001000, 6, 6, 3),
    (0b000100, 6, 7, 3),
    (0b0000111, 7, 3, 0),
    (0b0000110, 7, 5, 1),
    (0b0000101, 7, 5, 2),
    (0b0000100, 7, 8, 3),
    (0b00000111, 8, 4, 0),
    (0b00000100, 8, 5, 0),
    (0b00000110, 8, 6, 1),
    (0b00000101, 8, 6, 2),
    (0b000000111, 9, 6, 0),
    (0b000000110, 9, 7, 1),
    (0b000000101, 9, 7, 2),
    (0b000000100, 9, 9, 3),
    (0b00000001111, 11, 7, 0),
    (0b00000001011, 11, 8, 0),
    (0b00000001110, 11, 8, 1),
    (0b00000001101, 11, 8, 2),
    (0b00000001010, 11, 9, 1),
    (0b00000001001, 11, 9, 2),
    (0b00000001100, 11, 10, 3),
    (0b00000001000, 11, 11, 3),
    (0b000000001111, 12, 9, 0),
    (0b000000001011, 12, 10, 0),
    (0b000000001110, 12, 10, 1),
    (0b000000001101, 12, 10, 2),
    (0b000000001000, 12, 11, 0),
    (0b000000001010, 12, 11, 1),
    (0b000000001001, 12, 11, 2),
    (0b000000001100, 12, 12, 3),
    (0b0000000001111, 13, 12, 0),
    (0b0000000001110, 13, 12, 1),
    (0b0000000001101, 13, 12, 2),
    (0b0000000001011, 13, 13, 0),
    (0b0000000001010, 13, 13, 1),
    (0b0000000001001, 13, 13, 2),
    (0b0000000001100, 13, 13, 3),
    (0b0000000000111, 13, 14, 0),
    (0b0000000000110, 13, 14, 2),
    (0b0000000001000, 13, 14, 3),
    (0b0000000000001, 13, 15, 3),
    (0b00000000001011, 14, 14, 1),
    (0b00000000001001, 14, 15, 0),
    (0b00000000001000, 14, 15, 1),
    (0b00000000001010, 14, 15, 2),
    (0b00000000000111, 14, 16, 0),
    (0b00000000000110, 14, 16, 1),
    (0b00000000000101, 14, 16, 2),
    (0b00000000000100, 14, 16, 3),
];

/// Num-VLC2: nC ∈ [4, 8)
const COEFF_TOKEN_VLC2: &[(u32, u8, u32, u32)] = &[
    (0b1111, 4, 0, 0),
    (0b1110, 4, 1, 1),
    (0b1101, 4, 2, 2),
    (0b1100, 4, 3, 3),
    (0b1011, 4, 4, 3),
    (0b1010, 4, 5, 3),
    (0b1001, 4, 6, 3),
    (0b1000, 4, 7, 3),
    (0b01111, 5, 2, 1),
    (0b01100, 5, 3, 1),
    (0b01110, 5, 3, 2),
    (0b01010, 5, 4, 1),
    (0b01011, 5, 4, 2),
    (0b01000, 5, 5, 1),
    (0b01001, 5, 5, 2),
    (0b01101, 5, 8, 3),
    (0b001111, 6, 1, 0),
    (0b001011, 6, 2, 0),
    (0b001000, 6, 3, 0),
    (0b001110, 6, 6, 1),
    (0b001101, 6, 6, 2),
    (0b001010, 6, 7, 1),
    (0b001001, 6, 7, 2),
    (0b001100, 6, 9, 3),
    (0b0001111, 7, 4, 0),
    (0b0001011, 7, 5, 0),
    (0b0001001, 7, 6, 0),
    (0b0001000, 7, 7, 0),
    (0b0001110, 7, 8, 1),
    (0b0001101, 7, 8, 2),
    (0b0001010, 7, 9, 2),
    (0b0001100, 7, 10, 3),
    (0b00001111, 8, 8, 0),
    (0b00001011, 8, 9, 0),
    (0b00001110, 8, 9, 1),
    (0b00001010, 8, 10, 1),
    (0b00001101, 8, 10, 2),
    (0b00001001, 8, 11, 2),
    (0b00001100, 8, 11, 3),
    (0b00001000, 8, 12, 3),
    (0b000001111, 9, 10, 0),
    (0b000001011, 9, 11, 0),
    (0b000001110, 9, 11, 1),
    (0b000001000, 9, 12, 0),
    (0b000001010, 9, 12, 1),
    (0b000001101, 9, 12, 2),
    (0b000000111, 9, 13, 1),
    (0b000001001, 9, 13, 2),
    (0b000001100, 9, 13, 3),
    (0b0000001101, 10, 13, 0),
    (0b0000001001, 10, 14, 0),
    (0b0000001100, 10, 14, 1),
    (0b0000001011, 10, 14, 2),
    (0b0000001010, 10, 14, 3),
    (0b0000000101, 10, 15, 0),
    (0b0000001000, 10, 15, 1),
    (0b0000000111, 10, 15, 2),
    (0b0000000110, 10, 15, 3),
    (0b0000000001, 10, 16, 0),
    (0b0000000100, 10, 16, 1),
    (0b0000000011, 10, 16, 2),
    (0b0000000010, 10, 16, 3),
];

/// Num-VLC3: nC ∈ >= 8 (FLC, 6-bit fixed)
const COEFF_TOKEN_FLC: &[(u32, u8, u32, u32)] = &[
    (0b000011, 6, 0, 0),
    (0b000000, 6, 1, 0),
    (0b000001, 6, 1, 1),
    (0b000100, 6, 2, 0),
    (0b000101, 6, 2, 1),
    (0b000110, 6, 2, 2),
    (0b001000, 6, 3, 0),
    (0b001001, 6, 3, 1),
    (0b001010, 6, 3, 2),
    (0b001011, 6, 3, 3),
    (0b001100, 6, 4, 0),
    (0b001101, 6, 4, 1),
    (0b001110, 6, 4, 2),
    (0b001111, 6, 4, 3),
    (0b010000, 6, 5, 0),
    (0b010001, 6, 5, 1),
    (0b010010, 6, 5, 2),
    (0b010011, 6, 5, 3),
    (0b010100, 6, 6, 0),
    (0b010101, 6, 6, 1),
    (0b010110, 6, 6, 2),
    (0b010111, 6, 6, 3),
    (0b011000, 6, 7, 0),
    (0b011001, 6, 7, 1),
    (0b011010, 6, 7, 2),
    (0b011011, 6, 7, 3),
    (0b011100, 6, 8, 0),
    (0b011101, 6, 8, 1),
    (0b011110, 6, 8, 2),
    (0b011111, 6, 8, 3),
    (0b100000, 6, 9, 0),
    (0b100001, 6, 9, 1),
    (0b100010, 6, 9, 2),
    (0b100011, 6, 9, 3),
    (0b100100, 6, 10, 0),
    (0b100101, 6, 10, 1),
    (0b100110, 6, 10, 2),
    (0b100111, 6, 10, 3),
    (0b101000, 6, 11, 0),
    (0b101001, 6, 11, 1),
    (0b101010, 6, 11, 2),
    (0b101011, 6, 11, 3),
    (0b101100, 6, 12, 0),
    (0b101101, 6, 12, 1),
    (0b101110, 6, 12, 2),
    (0b101111, 6, 12, 3),
    (0b110000, 6, 13, 0),
    (0b110001, 6, 13, 1),
    (0b110010, 6, 13, 2),
    (0b110011, 6, 13, 3),
    (0b110100, 6, 14, 0),
    (0b110101, 6, 14, 1),
    (0b110110, 6, 14, 2),
    (0b110111, 6, 14, 3),
    (0b111000, 6, 15, 0),
    (0b111001, 6, 15, 1),
    (0b111010, 6, 15, 2),
    (0b111011, 6, 15, 3),
    (0b111100, 6, 16, 0),
    (0b111101, 6, 16, 1),
    (0b111110, 6, 16, 2),
    (0b111111, 6, 16, 3),
];

const TOTAL_ZEROS_TABLES: [&[(u32, u8, u32)]; 16] = [
    &[], // TC=0 — unused
    // TC = 1
    &[
        (0b1, 1, 0),
        (0b011, 3, 1),
        (0b010, 3, 2),
        (0b0011, 4, 3),
        (0b0010, 4, 4),
        (0b00011, 5, 5),
        (0b00010, 5, 6),
        (0b000011, 6, 7),
        (0b000010, 6, 8),
        (0b0000011, 7, 9),
        (0b0000010, 7, 10),
        (0b00000011, 8, 11),
        (0b00000010, 8, 12),
        (0b000000011, 9, 13),
        (0b000000010, 9, 14),
        (0b000000001, 9, 15),
    ],
    // TC = 2
    &[
        (0b111, 3, 0),
        (0b110, 3, 1),
        (0b101, 3, 2),
        (0b100, 3, 3),
        (0b011, 3, 4),
        (0b0101, 4, 5),
        (0b0100, 4, 6),
        (0b0011, 4, 7),
        (0b0010, 4, 8),
        (0b00011, 5, 9),
        (0b00010, 5, 10),
        (0b000011, 6, 11),
        (0b000010, 6, 12),
        (0b000001, 6, 13),
        (0b000000, 6, 14),
    ],
    // TC = 3
    &[
        (0b111, 3, 1),
        (0b110, 3, 2),
        (0b101, 3, 3),
        (0b100, 3, 6),
        (0b011, 3, 7),
        (0b0101, 4, 0),
        (0b0100, 4, 4),
        (0b0011, 4, 5),
        (0b0010, 4, 8),
        (0b00011, 5, 9),
        (0b00010, 5, 10),
        (0b00001, 5, 12),
        (0b000001, 6, 11),
        (0b000000, 6, 13),
    ],
    // TC = 4
    &[
        (0b111, 3, 1),
        (0b110, 3, 4),
        (0b101, 3, 5),
        (0b100, 3, 6),
        (0b011, 3, 8),
        (0b0101, 4, 2),
        (0b0100, 4, 3),
        (0b0011, 4, 7),
        (0b0010, 4, 9),
        (0b00011, 5, 0),
        (0b00010, 5, 10),
        (0b00001, 5, 11),
        (0b00000, 5, 12),
    ],
    // TC = 5
    &[
        (0b111, 3, 3),
        (0b110, 3, 4),
        (0b101, 3, 5),
        (0b100, 3, 6),
        (0b011, 3, 7),
        (0b0101, 4, 0),
        (0b0100, 4, 1),
        (0b0011, 4, 2),
        (0b0010, 4, 8),
        (0b0001, 4, 10),
        (0b00001, 5, 9),
        (0b00000, 5, 11),
    ],
    // TC = 6
    &[
        (0b111, 3, 2),
        (0b110, 3, 3),
        (0b101, 3, 4),
        (0b100, 3, 5),
        (0b011, 3, 6),
        (0b010, 3, 7),
        (0b001, 3, 9),
        (0b0001, 4, 8),
        (0b00001, 5, 1),
        (0b000001, 6, 0),
        (0b000000, 6, 10),
    ],
    // TC = 7
    &[
        (0b11, 2, 5),
        (0b101, 3, 2),
        (0b100, 3, 3),
        (0b011, 3, 4),
        (0b010, 3, 6),
        (0b001, 3, 8),
        (0b0001, 4, 7),
        (0b00001, 5, 1),
        (0b000001, 6, 0),
        (0b000000, 6, 9),
    ],
    // TC = 8
    &[
        (0b11, 2, 4),
        (0b10, 2, 5),
        (0b011, 3, 3),
        (0b010, 3, 6),
        (0b001, 3, 7),
        (0b0001, 4, 1),
        (0b00001, 5, 2),
        (0b000001, 6, 0),
        (0b000000, 6, 8),
    ],
    // TC = 9
    &[
        (0b11, 2, 3),
        (0b10, 2, 4),
        (0b01, 2, 6),
        (0b001, 3, 5),
        (0b0001, 4, 2),
        (0b00001, 5, 7),
        (0b000001, 6, 0),
        (0b000000, 6, 1),
    ],
    // TC = 10
    &[
        (0b11, 2, 3),
        (0b10, 2, 4),
        (0b01, 2, 5),
        (0b001, 3, 2),
        (0b0001, 4, 6),
        (0b00001, 5, 0),
        (0b00000, 5, 1),
    ],
    // TC = 11
    &[
        (0b1, 1, 4),
        (0b001, 3, 2),
        (0b010, 3, 3),
        (0b011, 3, 5),
        (0b0000, 4, 0),
        (0b0001, 4, 1),
    ],
    // TC = 12
    &[
        (0b1, 1, 3),
        (0b01, 2, 2),
        (0b001, 3, 4),
        (0b0000, 4, 0),
        (0b0001, 4, 1),
    ],
    // TC = 13
    &[
        (0b1, 1, 2),
        (0b01, 2, 3),
        (0b000, 3, 0),
        (0b001, 3, 1),
    ],
    // TC = 14
    &[
        (0b1, 1, 2),
        (0b00, 2, 0),
        (0b01, 2, 1),
    ],
    // TC = 15
    &[
        (0b0, 1, 0),
        (0b1, 1, 1),
    ],
];

const RUN_BEFORE_TABLES: [&[(u32, u8, u32)]; 16] = [
    &[], // zerosLeft=0 — unused
    // zerosLeft = 1
    &[
        (0b1, 1, 0),
        (0b0, 1, 1),
    ],
    // zerosLeft = 2
    &[
        (0b1, 1, 0),
        (0b01, 2, 1),
        (0b00, 2, 2),
    ],
    // zerosLeft = 3
    &[
        (0b11, 2, 0),
        (0b10, 2, 1),
        (0b01, 2, 2),
        (0b00, 2, 3),
    ],
    // zerosLeft = 4
    &[
        (0b11, 2, 0),
        (0b10, 2, 1),
        (0b01, 2, 2),
        (0b001, 3, 3),
        (0b000, 3, 4),
    ],
    // zerosLeft = 5
    &[
        (0b11, 2, 0),
        (0b10, 2, 1),
        (0b011, 3, 2),
        (0b010, 3, 3),
        (0b001, 3, 4),
        (0b000, 3, 5),
    ],
    // zerosLeft = 6
    &[
        (0b11, 2, 0),
        (0b000, 3, 1),
        (0b001, 3, 2),
        (0b011, 3, 3),
        (0b010, 3, 4),
        (0b101, 3, 5),
        (0b100, 3, 6),
    ],
    // zerosLeft = 7 (>= 7, shared table)
    &[
        (0b111, 3, 0),
        (0b110, 3, 1),
        (0b101, 3, 2),
        (0b100, 3, 3),
        (0b011, 3, 4),
        (0b010, 3, 5),
        (0b001, 3, 6),
        (0b0001, 4, 7),
        (0b00001, 5, 8),
        (0b000001, 6, 9),
        (0b0000001, 7, 10),
        (0b00000001, 8, 11),
        (0b000000001, 9, 12),
        (0b0000000001, 10, 13),
        (0b00000000001, 11, 14),
    ],
    // zerosLeft = 8 (>= 7, shared table)
    &[
        (0b111, 3, 0),
        (0b110, 3, 1),
        (0b101, 3, 2),
        (0b100, 3, 3),
        (0b011, 3, 4),
        (0b010, 3, 5),
        (0b001, 3, 6),
        (0b0001, 4, 7),
        (0b00001, 5, 8),
        (0b000001, 6, 9),
        (0b0000001, 7, 10),
        (0b00000001, 8, 11),
        (0b000000001, 9, 12),
        (0b0000000001, 10, 13),
        (0b00000000001, 11, 14),
    ],
    // zerosLeft = 9 (>= 7, shared table)
    &[
        (0b111, 3, 0),
        (0b110, 3, 1),
        (0b101, 3, 2),
        (0b100, 3, 3),
        (0b011, 3, 4),
        (0b010, 3, 5),
        (0b001, 3, 6),
        (0b0001, 4, 7),
        (0b00001, 5, 8),
        (0b000001, 6, 9),
        (0b0000001, 7, 10),
        (0b00000001, 8, 11),
        (0b000000001, 9, 12),
        (0b0000000001, 10, 13),
        (0b00000000001, 11, 14),
    ],
    // zerosLeft = 10 (>= 7, shared table)
    &[
        (0b111, 3, 0),
        (0b110, 3, 1),
        (0b101, 3, 2),
        (0b100, 3, 3),
        (0b011, 3, 4),
        (0b010, 3, 5),
        (0b001, 3, 6),
        (0b0001, 4, 7),
        (0b00001, 5, 8),
        (0b000001, 6, 9),
        (0b0000001, 7, 10),
        (0b00000001, 8, 11),
        (0b000000001, 9, 12),
        (0b0000000001, 10, 13),
        (0b00000000001, 11, 14),
    ],
    // zerosLeft = 11 (>= 7, shared table)
    &[
        (0b111, 3, 0),
        (0b110, 3, 1),
        (0b101, 3, 2),
        (0b100, 3, 3),
        (0b011, 3, 4),
        (0b010, 3, 5),
        (0b001, 3, 6),
        (0b0001, 4, 7),
        (0b00001, 5, 8),
        (0b000001, 6, 9),
        (0b0000001, 7, 10),
        (0b00000001, 8, 11),
        (0b000000001, 9, 12),
        (0b0000000001, 10, 13),
        (0b00000000001, 11, 14),
    ],
    // zerosLeft = 12 (>= 7, shared table)
    &[
        (0b111, 3, 0),
        (0b110, 3, 1),
        (0b101, 3, 2),
        (0b100, 3, 3),
        (0b011, 3, 4),
        (0b010, 3, 5),
        (0b001, 3, 6),
        (0b0001, 4, 7),
        (0b00001, 5, 8),
        (0b000001, 6, 9),
        (0b0000001, 7, 10),
        (0b00000001, 8, 11),
        (0b000000001, 9, 12),
        (0b0000000001, 10, 13),
        (0b00000000001, 11, 14),
    ],
    // zerosLeft = 13 (>= 7, shared table)
    &[
        (0b111, 3, 0),
        (0b110, 3, 1),
        (0b101, 3, 2),
        (0b100, 3, 3),
        (0b011, 3, 4),
        (0b010, 3, 5),
        (0b001, 3, 6),
        (0b0001, 4, 7),
        (0b00001, 5, 8),
        (0b000001, 6, 9),
        (0b0000001, 7, 10),
        (0b00000001, 8, 11),
        (0b000000001, 9, 12),
        (0b0000000001, 10, 13),
        (0b00000000001, 11, 14),
    ],
    // zerosLeft = 14 (>= 7, shared table)
    &[
        (0b111, 3, 0),
        (0b110, 3, 1),
        (0b101, 3, 2),
        (0b100, 3, 3),
        (0b011, 3, 4),
        (0b010, 3, 5),
        (0b001, 3, 6),
        (0b0001, 4, 7),
        (0b00001, 5, 8),
        (0b000001, 6, 9),
        (0b0000001, 7, 10),
        (0b00000001, 8, 11),
        (0b000000001, 9, 12),
        (0b0000000001, 10, 13),
        (0b00000000001, 11, 14),
    ],
    // zerosLeft = 15 (>= 7, shared table)
    &[
        (0b111, 3, 0),
        (0b110, 3, 1),
        (0b101, 3, 2),
        (0b100, 3, 3),
        (0b011, 3, 4),
        (0b010, 3, 5),
        (0b001, 3, 6),
        (0b0001, 4, 7),
        (0b00001, 5, 8),
        (0b000001, 6, 9),
        (0b0000001, 7, 10),
        (0b00000001, 8, 11),
        (0b000000001, 9, 12),
        (0b0000000001, 10, 13),
        (0b00000000001, 11, 14),
    ],
];

/// Chroma DC coeff_token (4:2:0, max_coeff=4). Source: FFmpeg chroma_dc_coeff_token.
const CHROMA_DC_COEFF_TOKEN: &[(u32, u8, u32, u32)] = &[
    (0b1, 1, 1, 1),
    (0b01, 2, 0, 0),
    (0b001, 3, 2, 2),
    (0b000111, 6, 1, 0),
    (0b000100, 6, 2, 0),
    (0b000110, 6, 2, 1),
    (0b000011, 6, 3, 0),
    (0b000101, 6, 3, 3),
    (0b000010, 6, 4, 0),
    (0b0000011, 7, 3, 1),
    (0b0000010, 7, 3, 2),
    (0b0000000, 7, 4, 3),
    (0b00000011, 8, 4, 1),
    (0b00000010, 8, 4, 2),
];

const CHROMA_DC_TOTAL_ZEROS: [&[(u32, u8, u32)]; 4] = [
    &[], // TC=0 — unused
    // TC = 1
    &[
        (0b1, 1, 0),
        (0b01, 2, 1),
        (0b001, 3, 2),
        (0b000, 3, 3),
    ],
    // TC = 2
    &[
        (0b1, 1, 0),
        (0b01, 2, 1),
        (0b00, 2, 2),
    ],
    // TC = 3
    &[
        (0b1, 1, 0),
        (0b0, 1, 1),
    ],
];

/// 解码 4:2:0 色度 DC 块 (4 个系数)。
///
/// H.264 标准 §9.2.1 中 chromaDCLevel 的解码路径:
/// - 用 nC=-1 专用 VLC 表 (CHROMA_DC_COEFF_TOKEN)
/// - level 解码与普通 4x4 相同
/// - totalZeros 用 CHROMA_DC_TOTAL_ZEROS 表
/// - run_before 复用通用表
///
/// 返回 4 个系数的数组, 顺序为 [d00, d01, d10, d11] (行优先)。
pub fn decode_chroma_dc(br: &mut BitReader) -> ([i16; 4], u32) {
    let mut coeffs = [0i16; 4];

    let (total_coeff, trailing_ones) = match_vlc_coeff_token(br, CHROMA_DC_COEFF_TOKEN);

    if total_coeff == 0 {
        return (coeffs, 0);
    }
    let trailing_ones = trailing_ones.min(total_coeff).min(3);

    let mut level = vec![0i32; total_coeff as usize];

    // 1. 解码 trailing ones 符号
    if trailing_ones > 0 {
        for i in 0..trailing_ones {
            let sign = if br.read_bit() == 1 { -1 } else { 1 };
            let idx = total_coeff as usize - 1 - i as usize;
            if idx < level.len() {
                level[idx] = sign;
            }
        }
    }

    // 2. 解码剩余 level
    if total_coeff > trailing_ones {
        let num_levels = total_coeff - trailing_ones;
        let mut suffix_length = if total_coeff > 10 && trailing_ones < 3 { 1 } else { 0 };
        for i in 0..num_levels {
            let idx = total_coeff as usize - 1 - trailing_ones as usize - i as usize;
            let lvl = read_level_vlc(br, suffix_length);
            level[idx] = lvl;
            // H.264 §9.2.2: 一次迭代最多增加 1
            if suffix_length == 0 {
                suffix_length = 1;
            } else if suffix_length < 6 {
                let threshold = 3 << (suffix_length - 1);
                if lvl.abs() > threshold {
                    suffix_length += 1;
                }
            }
        }
    }

    // 3. 解码 totalZeros (max_coeff=4)
    let total_zeros = if total_coeff < 4 && total_coeff >= 1 {
        let table = CHROMA_DC_TOTAL_ZEROS[total_coeff as usize];
        match_vlc(br, table)
    } else {
        0
    };

    // 4. 解码 run_before
    let mut zeros_left = total_zeros;
    let mut run_before = vec![0u32; total_coeff as usize];
    for item in run_before.iter_mut().take(total_coeff as usize - 1) {
        if zeros_left > 0 {
            *item = read_run_before_vlc(br, &mut zeros_left);
        }
    }
    if total_coeff > 0 {
        run_before[total_coeff as usize - 1] = zeros_left;
    }

    // 5. 填充系数数组（顺序与 4x4 一致：从最高频到最低频）
    let mut pos = 0usize;
    for i in (0..total_coeff as usize).rev() {
        pos += run_before[i] as usize;
        if pos >= 4 {
            break;
        }
        coeffs[pos] = level[i] as i16;
        pos += 1;
    }

    (coeffs, total_coeff)
}

// ─── 公开 API ─────────────────────────────────────────────────────────

/// 解码一个 4x4 块的残差系数。
///
/// * `n_c` — 左侧和上侧相邻块的非零系数数目（用于选择 VLC 表）。
/// * `max_coeff` — 最大系数数（通常 16，色度 DC 为 4 或 15）。
pub fn decode_block(br: &mut BitReader, n_c: u32, max_coeff: u32) -> CavlcResult {
    let mut coeffs = [0i16; 16];

    let (total_coeff, trailing_ones) = read_coeff_token(br, n_c);

    if total_coeff == 0 {
        return CavlcResult {
            coeffs,
            total_coeff: 0,
        };
    }

    // 防御性 clamp：H.264 标准保证 trailing_ones <= min(total_coeff, 3)
    // 但 coeff_token 解码表可能返回无效组合，这里确保不会下溢
    let trailing_ones = trailing_ones.min(total_coeff).min(3);

    let mut level = vec![0i32; total_coeff as usize];

    // 2. 读取 trailing ones 的符号
    if trailing_ones > 0 {
        for i in 0..trailing_ones {
            let sign = if br.read_bit() == 1 { -1 } else { 1 };
            let idx = total_coeff as usize - 1 - i as usize;
            if idx < level.len() {
                level[idx] = sign;
            }
        }
    }

    // 3. 读取剩余非零系数的 Level（幅度）
    if total_coeff > trailing_ones {
        let num_levels = total_coeff - trailing_ones;
        let mut suffix_length = if total_coeff > 10 && trailing_ones < 3 {
            1u32
        } else {
            0u32
        };

        for i in 0..num_levels {
            let idx = total_coeff as usize - 1 - trailing_ones as usize - i as usize;
            let lvl = read_level_vlc(br, suffix_length);
            level[idx] = lvl;

            // H.264 §9.2.2: 一次迭代最多增加 1
            if suffix_length == 0 {
                suffix_length = 1;
            } else if suffix_length < 6 {
                let threshold = 3 << (suffix_length - 1);
                if lvl.abs() > threshold {
                    suffix_length += 1;
                }
            }
        }
    }

    // 4. 读取 totalZeros
    let total_zeros = if total_coeff < max_coeff {
        read_total_zeros_vlc(br, total_coeff)
    } else {
        0
    };

    // 5. 读取 run_before
    let mut zeros_left = total_zeros;
    let mut run_before = vec![0u32; total_coeff as usize];
    for item in run_before.iter_mut().take(total_coeff as usize - 1) {
        if zeros_left > 0 {
            *item = read_run_before_vlc(br, &mut zeros_left);
        }
    }
    run_before[total_coeff as usize - 1] = zeros_left;

    // 6. 填充系数数组（Zigzag 扫描顺序）
    let mut zigzag_pos = 0usize;
    for i in (0..total_coeff as usize).rev() {
        zigzag_pos += run_before[i] as usize;
        if zigzag_pos >= 16 {
            break;
        }
        let (row, col) = ZIGZAG_4x4[zigzag_pos];
        coeffs[(row as usize) * 4 + (col as usize)] = level[i] as i16;
        zigzag_pos += 1;
    }

    CavlcResult {
        coeffs,
        total_coeff,
    }
}

/// 计算 nC（相邻块的非零系数数）。
#[allow(dead_code)]
pub fn calc_nc(n_a: u32, n_b: u32) -> u32 {
    (n_a + n_b + 1) >> 1
}

// ─── 内部 VLC 解码函数 ────────────────────────────────────────────────

/// coeff_token 解码（H.264 Table 9-5）。
fn read_coeff_token(br: &mut BitReader, n_c: u32) -> (u32, u32) {
    let table = if n_c < 2 {
        COEFF_TOKEN_VLC0
    } else if n_c < 4 {
        COEFF_TOKEN_VLC1
    } else if n_c < 8 {
        COEFF_TOKEN_VLC2
    } else {
        COEFF_TOKEN_FLC
    };
    match_vlc_coeff_token(br, table)
}

/// Level 解码（H.264 标准 9.2.2）。
fn read_level_vlc(br: &mut BitReader, suffix_length: u32) -> i32 {
    let prefix = read_level_prefix(br);
    let level_code = (prefix << suffix_length) + br.read_bits(suffix_length as u8);

    if level_code.is_multiple_of(2) {
        ((level_code + 2) >> 1) as i32
    } else {
        -(((level_code + 1) >> 1) as i32)
    }
}

fn read_level_prefix(br: &mut BitReader) -> u32 {
    let mut leading_zeros = 0u32;
    while br.read_bit() == 0 {
        leading_zeros += 1;
        if leading_zeros > 15 {
            break;
        }
    }
    leading_zeros
}

/// totalZeros 解码（H.264 Table 9-7）。
fn read_total_zeros_vlc(br: &mut BitReader, total_coeff: u32) -> u32 {
    if total_coeff == 0 || total_coeff >= 16 {
        return 0;
    }
    match_vlc(br, TOTAL_ZEROS_TABLES[total_coeff as usize])
}

/// run_before 解码（H.264 Table 9-10）。
fn read_run_before_vlc(br: &mut BitReader, zeros_left: &mut u32) -> u32 {
    let zl = (*zeros_left).min(15) as usize;
    let table = if zl <= 6 {
        RUN_BEFORE_TABLES[zl]
    } else {
        RUN_BEFORE_TABLES[7] // zerosLeft > 6 共用同一张表
    };
    let result = match_vlc(br, table);
    *zeros_left -= result;
    result
}

// ─── 通用 VLC 匹配 ─────────────────────────────────────────────────────

/// 从位流中逐位匹配 VLC 表，返回对应 value。
/// 表按 (codeword, length, value) 的顺序排列（前缀码，code 左对齐）。
fn match_vlc(br: &mut BitReader, table: &[(u32, u8, u32)]) -> u32 {
    let mut acc: u32 = 0;
    let mut bits: u8 = 0;
    for &(codeword, len, value) in table {
        while bits < len {
            acc = (acc << 1) | br.read_bit();
            bits += 1;
        }
        let mask = if len == 32 { !0u32 } else { (1u32 << len) - 1 };
        let top = acc >> (bits - len);
        if top & mask == codeword & mask {
            return value;
        }
    }
    0
}

/// coeff_token 专用 VLC 匹配，返回 (total_coeff, trailing_ones)。
fn match_vlc_coeff_token(br: &mut BitReader, table: &[(u32, u8, u32, u32)]) -> (u32, u32) {
    let mut acc: u32 = 0;
    let mut bits: u8 = 0;
    for &(codeword, len, total_coeff, trailing_ones) in table {
        while bits < len {
            acc = (acc << 1) | br.read_bit();
            bits += 1;
        }
        let mask = if len == 32 { !0u32 } else { (1u32 << len) - 1 };
        let top = acc >> (bits - len);
        if top & mask == codeword & mask {
            return (total_coeff, trailing_ones);
        }
    }
    (0, 0)
}
